org.gradle.jvmargs=-Xmx4G

android.useAndroidX=true
android.enableJetifier=true

org.gradle.java.home=C:\\Program Files\\Java\\jdk-17

# Required for new Google Play policy (16KB memory pages)
android.ndkVersion=26.1.10909125

# Recommended for stability with latest AGP
#android.enableDexingArtifactTransform=false

